version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: nestjs-app
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:14.2
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
